### ISSUE TITLE
AdaKerja Review

### ISSUE THREAD

**Issue by IrfaanDzakiy** [bram-abe/serverless-fb-messanger-app#1]
Hi Bram!. I'm Irfaan from AdaKerja. Thank you so much for your submission. Before we review your submission, could you share a live endpoint that we can use to test your app?
Thanks!

**Comment by IrfaanDzakiy** [comment]
@bram-abe You can send the endpoint to irfaan@adakerja.com
Thanks!

**Comment by IrfaanDzakiy** [comment]
Hi @bram-abe. After reviewing your work, here is my review and question.

Review:
[+] Correct birthday calculation
[+] Clear README and Demo
[+] Using AWS service (Plus point 👍🏼 )
[+] Working API

[-] No proper testing for REST API.
[-] No checking for birthday input

Question:
1. How does your app handle birthday input that are not in intended format? (`YYYY-MM-DD` if i'm not mistaken`)
2. How does your app handle error that happen on REST API? Does it give information as to what cause the error?
3. How can you enforce testing on the REST API?

Please address my reviews and questions so we can proceed to the next step :)

Thank You!

**Comment by bram-abe** [comment]
Hi @IrfaanDzakiy thank you for the review.
 
> 1. How does your app handle birthday input that are not in intended format? (`YYYY-MM-DD` if i'm not mistaken`)

It can be improved by using regex test like this : /^([0-9]{4})\-([0-9]{2})\-([0-9]{2})$/

> 2. How does your app handle error that happen on REST API? Does it give information as to what cause the error?

The API part is consist of two main different part ;
	A. AWS Lambda function where the logic reside
	B. AWS API Gateway as REST Server

- Point A all errors caused by code or database integration will be caught in try-catch and writed to console. It is standard practice to log AWS Lambda when using AWS Cloudwatch as a log stack that only logs what is written to the console. Of course you can use any log library other than AWS Cloudwatch.
- Point B it can be improved by setting up the AWS API Gateway to log all request with AWS Cloudwatch log groups. We can set it via serverless.yml (IaS template) and some additional settings via AWS console

> 3. How can you enforce testing on the REST API?

This can be implemented by writing test cases and automated test on CI/CD pipeline. This will need to setup additional CI/CD pipeline resources. The goal is the code deployment should be rejected if any test case fails

**Comment by bram-abe** [comment]
@IrfaanDzakiy Sure 👍🏻 

I will working on it tonight after work and breaking the fast.

**Comment by bram-abe** [comment]
> Hi @bram-abe !. Thank you for the answers, i really liked it 👍🏼. Could you please improve your code based on your answer, so we could move on to the next step?

Hai @IrfaanDzakiy please check the update.
